from gui.Scaleform.genConsts.PERSONAL_MISSIONS_ALIASES import PERSONAL_MISSIONS_ALIASES
PERSONAL_MISSIONS_ALIASES.REGION_COMPLETED = PERSONAL_MISSIONS_ALIASES.REGION_NOT_AVAILABLE
print '[LOAD_MOD]:  [mod_personalMissionColored 1.04 (18-12-2017), by spoter]'
